stages:
  - type: REPLACE_LIST
    sampler:
      type: CELLULAR
      return: CellValue
      frequency: 1 / 1000 / ${customization.yml:variation-scale} / ${customization.yml:global-scale}
    
    default-from: ice-cap-flat
    default-to:
      - ICE_SPIKES: 1
    to:
        ice-cap:
          - SNOWY_MOUNTAINS: 1
        ice-cap-highlands:
          - SNOWY_MOUNTAINS: 1
        
        tundra-flat:
          - TUNDRA: 1
        tundra:
          - TUNDRA: 1
        tundra-highlands:
          - SNOWY_MOUNTAINS: 1
        
        polar-coast-flat:
          - FROZEN_BEACH: 1
        polar-coast:
          - SNOWY_SEA_CAVES: 1
        polar-coast-highlands:
          - SNOWY_SEA_CAVES: 1
  
        polar-plateau:
          - COLD_DESERT_PLATEAU: 1
          
        polar-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
          
        polar-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1
  
        polar-ocean:
          - FROZEN_OCEAN: 1
        polar-deep-ocean:
          - FROZEN_DEEP_OCEAN: 1
  
        boreal-hot-summer-flat:
          - AUTUMNAL_FOREST: 1
          - FLOWERING_AUTUMNAL_FOREST: 1
          - BIRCH_FOREST: 1
        boreal-hot-summer:
          - AUTUMNAL_FOREST: 1
          - FLOWERING_AUTUMNAL_FOREST: 1
          - BIRCH_FOREST: 1
        boreal-hot-summer-highlands:
          - MOUNTAINS: 1
        
        boreal-warm-summer-flat:
          - AUTUMNAL_FOREST: 1
          - FLOWERING_AUTUMNAL_FOREST: 1
          - BIRCH_FOREST: 1
        boreal-warm-summer:
          - EVERGREEN_FOREST: 1
          - REDWOOD_FOREST: 1
          - TAIGA: 5
        boreal-warm-summer-highlands:
          - MOUNTAINS: 1

        boreal-cold-summer-flat:
          - TAIGA: 1
        boreal-cold-summer:
          - TAIGA: 1
        boreal-cold-summer-highlands:
          - MOUNTAINS: 1
      
        boreal-very-cold-winter-flat:
          - TAIGA: 1
        boreal-very-cold-winter:
          - SNOWY_MEADOW: 1
        boreal-very-cold-winter-highlands:
          - SNOWY_MOUNTAINS: 1
        
        boreal-dry-winter-hot-summer-flat:
          - AUTUMNAL_FOREST: 1
          - FLOWERING_AUTUMNAL_FOREST: 1
          - BIRCH_FOREST: 1
        boreal-dry-winter-hot-summer:
          - TAIGA: 1
        boreal-dry-winter-hot-summer-highlands:
          - MOUNTAINS: 1

        boreal-dry-winter-warm-summer-flat:
          - TAIGA: 1
        boreal-dry-winter-warm-summer:
          - TAIGA: 1
        boreal-dry-winter-warm-summer-highlands:
          - MOUNTAINS: 1

        boreal-dry-winter-cold-summer-flat:
          - SNOWY_MEADOW: 1
        boreal-dry-winter-cold-summer:
          - SNOWY_MEADOW: 1
        boreal-dry-winter-cold-summer-highlands:
          - SNOWY_MOUNTAINS: 1

        boreal-dry-winter-very-cold-summer-flat:
          - SNOWY_MEADOW: 1
        boreal-dry-winter-very-cold-summer:
          - SNOWY_MEADOW: 1
        boreal-dry-winter-very-cold-summer-highlands:
          - SNOWY_MOUNTAINS: 1

        boreal-coast-flat:
          - ROCKY_ARCHIPELAGO: 5
          - SHALE_BEACH: 1
        boreal-coast:
          - ROCKY_SEA_CAVES: 1
        boreal-coast-highlands:
          - ROCKY_SEA_CAVES: 1
  
        boreal-plateau:
          - BOREAL_PLATEAU: 1
        
        boreal-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        boreal-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1
  
        boreal-ocean:
          - COLD_OCEAN: 1
        boreal-deep-ocean:
          - COLD_DEEP_OCEAN: 1
  
        temperate-mediterranean-hot-summer-flat:
          - PALM_FOREST: 1
          - CHAPARRAL: 1
          - MOORLAND: 1
        temperate-mediterranean-hot-summer:
          - CHAPARRAL: 1
          - MOORLAND: 1
        temperate-mediterranean-hot-summer-highlands:
          - DRY_TEMPERATE_MOUNTAINS: 1
          - DRY_TEMPERATE_WHITE_MOUNTAINS: 1

        temperate-mediterranean-warm-summer-flat:
          - PALM_FOREST: 1
          - CHAPARRAL: 1
          - MOORLAND: 1
        temperate-mediterranean-warm-summer:
          - CHAPARRAL: 1
          - MOORLAND: 1
        temperate-mediterranean-warm-summer-highlands:
          - DRY_TEMPERATE_MOUNTAINS: 1
          - DRY_TEMPERATE_WHITE_MOUNTAINS: 1

        temperate-hot-summer-flat:
          - PLAINS: 1
          - ALIEN_MARSH: 1
        temperate-hot-summer:
          - WOODED_BUTTES: 1
          - TEMPERATE_OVERPASS: 1
        temperate-hot-summer-highlands:
          - HIGHLANDS: 1
          - TEMPERATE_ALPHA_MOUNTAINS: 1
          - TEMPERATE_MOUNTAINS: 1

        temperate-warm-summer-flat:
          - FLOWERING_FOREST: 1
          - RAINFOREST: 1
          - BROADLEAF_FOREST: 1
          - DARK_FOREST: 1
          - SAKURA_GROVE: 1
          - WOODED_BUTTES: 1
        temperate-warm-summer:
          - FLOWERING_FOREST: 1
          - RAINFOREST: 1
          - BROADLEAF_FOREST: 1
          - DARK_FOREST: 1
          - SAKURA_GROVE: 1
          - WOODED_BUTTES: 1
        temperate-warm-summer-highlands:
          - HIGHLANDS: 1
          - TEMPERATE_ALPHA_MOUNTAINS: 1
          - TEMPERATE_MOUNTAINS: 1

        temperate-cold-summer-flat:
          - FLOWERING_FOREST: 1
          - RAINFOREST: 1
          - BROADLEAF_FOREST: 1
          - DARK_FOREST: 1
          - SAKURA_GROVE: 1
          - WOODED_BUTTES: 1
        temperate-cold-summer:
          - FLOWERING_FOREST: 1
          - RAINFOREST: 1
          - BROADLEAF_FOREST: 1
          - DARK_FOREST: 1
          - SAKURA_GROVE: 1
          - WOODED_BUTTES: 1
        temperate-cold-summer-highlands:
          - HIGHLANDS: 1
          - TEMPERATE_ALPHA_MOUNTAINS: 1
          - TEMPERATE_MOUNTAINS: 1

        temperate-coast-flat:
          - BEACH: 1
        temperate-coast:
          - TEMPERATE_SEA_ARCHES: 1
        temperate-coast-highlands:
          - TEMPERATE_SEA_ARCHES: 1

        temperate-plateau:
          - TEMPERATE_PLATEAU: 1
        
        temperate-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        temperate-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1

        temperate-ocean:
          - OCEAN: 1
        temperate-deep-ocean:
          - DEEP_OCEAN: 1

        hot-desert-flat:
          - DESERT: 5
          - SALT_FLATS: 1
        hot-desert:
          - DESERT: 10
          - DESERT_PILLARS: 1
          - DESERT_SPIKES: 1
          - DESERT_SPIKES_GOLD: 1
          - ROCKY_DESERT: 4
        hot-desert-highlands:
          - ARID_HIGHLANDS: 1
          - BADLANDS_BUTTES: 1
          - BADLANDS_MOUNTAINS: 1
          - CRACKED_BADLANDS_PLATEAU: 1
      
        hot-steppe-flat:
          - XERIC_SHRUBLAND: 1
          - ARID_SPIKES: 1
        hot-steppe:
          - XERIC_SHRUBLAND: 1
          - ARID_SPIKES: 1
        hot-steppe-highlands:
          - XERIC_MOUNTAINS: 1

        cold-desert-flat:
          - todo: 1
        cold-desert:
          - todo: 1
        cold-desert-highlands:
          - todo: 1

        cold-steppe-flat:
          - COLD_STEPPE: 1
        cold-steppe:
          - COLD_STEPPE: 1
        cold-steppe-highlands:
          - todo: 1

        cold-desert-plateau:
          - COLD_DESERT_PLATEAU: 1
        
        cold-desert-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        cold-desert-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1

        arid-coast-flat:
          - BEACH: 1
        arid-coast:
          - SANDSTONE_ARCHIPELAGO: 1
        arid-coast-highlands:
          - TERRACOTTA_SEA_CAVES: 1

        desert-plateau:
          - DESERT_PLATEAU: 1
        
        desert-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        desert-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1

        tropical-rainforest-flat:
          - BAMBOO_JUNGLE: 1
          - JUNGLE: 1
          - ROCKY_JUNGLE: 1
        tropical-rainforest:
          - BAMBOO_JUNGLE: 1
          - BAMBOO_PONDS: 1
          - JUNGLE: 1
          - ROCKY_JUNGLE: 1
        tropical-rainforest-highlands:
          - OVERGROWN_CLIFFS: 1

        tropical-monsoon-flat:
          - DRY_FOREST: 1
          - MONSOON_FOREST: 1
        tropical-monsoon:
          - DRY_FOREST: 1
          - MONSOON_FOREST: 1
        tropical-monsoon-highlands:
          - DRY_FOREST: 1
          - MONSOON_FOREST: 1

        tropical-savanna-dry-flat:
          - GRASS_SAVANNA: 1
          - SAVANNA: 1
        tropical-savanna-dry:
          - GRASS_SAVANNA: 1
          - SAVANNA: 1
        tropical-savanna-dry-highlands:
          - SAVANNA_OVERHANGS: 1

        tropical-savanna-wet-flat:
          - WET_SAVANNA: 1
        tropical-savanna-wet:
          - WET_SAVANNA: 1
        tropical-savanna-wet-highlands:
          - SAVANNA_OVERHANGS: 1

        tropical-coast-flat:
          - PALM_BEACH: 1
          - MANGROVE_SWAMP: 1
        tropical-coast: LUSH_SEA_CAVES
        tropical-coast-highlands: LUSH_SEA_CAVES

        tropical-plateau:
          - TROPICAL_PLATEAU: 1
        
        tropical-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        tropical-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1

        hot-ocean: TROPICAL_OCEAN
        hot-deep-ocean: TROPICAL_DEEP_OCEAN